export const agentsActionTypes = {
    ADD_AGENT_START: 'ADD_AGENT_START',
    ADD_AGENT_SUCCESS: 'ADD_AGENT_SUCCESS',
    ADD_AGENT_FAILURE: 'ADD_AGENT_FAILURE',
    GET_AGENTS_START: 'GET_AGENTS_START',
    GET_AGENTS_SUCCESS: 'GET_AGENTS_SUCCESS',
    GET_AGENTS_FAILURE: 'GET_AGENTS_FAILURE'
}