export const agentsActionTypes = {
    ADD_AGENT_START: 'ADD_AGENT_START',
    ADD_AGENT_SUCCESS: 'ADD_AGENT_SUCCESS',
    ADD_AGENT_FAILURE: 'ADD_AGENT_FAILURE',
    GET_AGENTS_START: 'GET_AGENTS_START',
    GET_AGENTS_SUCCESS: 'GET_AGENTS_SUCCESS',
    GET_AGENTS_FAILURE: 'GET_AGENTS_FAILURE',
    GET_AGENTS_SNAPSHOT: 'GET_AGENTS_SNAPSHOT',
    GET_AGENT_START: 'GET_AGENT_START',
    GET_AGENT_SUCCESS: 'GET_AGENT_SUCCESS',
    GET_AGENT_FAILURE: 'GET_AGENT_FAILURE',
    SEARCH_AGENT_START: 'SEARCH_AGENT_START',
    SEARCH_AGENT_SUCCESS: 'SEARCH_AGENT_SUCCESS',
    SEARCH_AGENT_FAILURE: 'SEARCH_AGENT_FAILURE'
}