export const activatedActionTypes = {
    GET_ACTIVATED_START: 'GET_ACTIVATED_START',
    GET_ACTIVATED_SUCCESS: 'GET_ACTIVATED_SUCCESS',
    GET_ACTIVATED_FAILURE: 'GET_ACTIVATED_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_ACTIVE_USERS_START: 'GET_MORE_ACTIVE_USERS_START',
    GET_MORE_ACTIVE_USERS_SUCCESS: 'GET_MORE_ACTIVE_USERS_SUCCESS',
    GET_MORE_ACTIVE_USERS_FAILURE: 'GET_MORE_ACTIVE_USERS_FAILURE',
}