export const usersActionTypes = {
    GET_INIT_USERS_START: 'GET_INIT_USERS_START',
    GET_INIT_USERS_SUCCESS: 'GET_INIT_USERS_SUCCESS',
    GET_INIT_USERS_FAILURE: 'GET_INIT_USERS_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_USERS_START: 'GET_MORE_USERS_START',
    GET_MORE_USERS_SUCCESS: 'GET_MORE_USERS_SUCCESS',
    GET_MORE_USERS_FAILURE: 'GET_MORE_USERS_FAILURE',
    GET_USERS_DETAIL_START: 'GET_USERS_DETAIL_START',
    GET_USERS_DETAIL_SUCCESS: 'GET_USERS_DETAIL_SUCCESS',
    GET_USERS_DETAIL_FAILURE: 'GET_USERS_DETAIL_FAILURE',
    UPDATE_ACTIVATION_STATUS_START: 'UPDATE_ACTIVATION_STATUS',
    UPDATE_ACTIVATION_STATUS_SUCCESS: 'UPDATE_ACTIVATION_STATUS_SUCCESS',
    UPDATE_ACTIVATION_STATUS_FAILURE: 'UPDATE_ACTIVATION_STATUS_FAILURE'
}