export const inactiveUsersActionTypes = {
    GET_INACTIVE_START: 'GET_INACTIVE_START',
    GET_INACTIVE_SUCCESS: 'GET_INACTIVE_SUCCESS',
    GET_INACTIVE_FAILURE: 'GET_INACTIVE_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_INACTIVE_START: 'GET_MORE_INACTIVE_START',
    GET_MORE_INACTIVE_SUCCESS: 'GET_MORE_INACTIVE_SUCCESS',
    GET_MORE_INACTIVE_FAILURE: 'GET_MORE_INACTIVE_FAILURE'
}