export const expiredActionTypes = {
    GET_EXPIRED_START: 'GET_EXPIRED_START',
    GET_EXPIRED_SUCCESS: 'GET_EXPIRED_SUCCESS',
    GET_EXPIRED_FAILURE: 'GET_EXPIRED_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_EXPIRED_START: 'GET_MORE_EXPIRED_START',
    GET_MORE_EXPIRED_SUCCESS: 'GET_MORE_EXPIRED_SUCCESS',
    GET_MORE_EXPIRED_FAILURE: 'GET_MORE_EXPIRED_FAILURE'
}